sudo: required
notifications:
  email: comses-dev@googlegroups.com
addons:
  apt:
    packages:
      - docker-ce
services:
  - docker
env:
  - COMPOSE_VERSION=1.25.3
before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod a+rx docker-compose
  - sudo mv docker-compose /usr/local/bin
  - sudo sysctl -w vm.max_map_count=262144
install:
  - docker --version
  - ./configure
script:
  - make secrets buildprod test-setup test
